server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: GymManager
  datasource:
    url: jdbc:h2:mem:gymmanager
    username: admin
    password: gymmanager
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
